### ISSUE TITLE
I know wasm support hexadecimal float format but binaryen does't provide it?

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#15]
hexadecimal format provide full access to IEEE 754 floating point representation and helping as avoiding implicit de-normalization and rounding errors which important for precise implementation of Math library and also will only one format for ```fma``` which currently not support, but will be in wasm-next.

Normal float point:
```ts
var f: double = 1e-6;
```
actually is ```9.999999974752427E-7``` after compiling

Hexadecimal format for the same float number:
```ts
var f: double = 0x1.0c6f7a0b5ed8dp-20;
```

Wasm support hexadecimal format for constants. So I start implementing [this format](https://github.com/MaxGraey/AssemblyScript/commit/b866688901369455ec1231d50b060c086cb61ec2) but binaryen can allow only numerics as argument for ```op.f64.const```=(

Is it possible emit raw command from string in binaryen?

**Comment by dcodeIO** [comment]
f64.const accepts two 32bit integers, which are the low and high bits of the corresponding 64-bit integer if precisely converted to a float. That's how they implement NaN, afaik.

**Comment by MaxGraey** [comment]
I see it ```f64.const_bits(low, high)```

**Comment by MaxGraey** [comment]
ok, I got it! Try to implement this

**Comment by MaxGraey** [comment]
I'm not deeply familiar with Typescript diagnostics so may be you little bit help me with it? I need skip checking legal literals which it seems fail before compiler stage. Just try to test [this branch](https://github.com/MaxGraey/AssemblyScript/tree/add-hexadecimal-format)

**Comment by dcodeIO** [comment]
Not sure if I can help you by looking at an entire branch of changes. What exactly do you want to do?

**Comment by MaxGraey** [comment]
I want skip diagnostic error:

```
return 0x1.0c6f7a0b5ed8dp-20;
                ~~
tests/test.ts(9,14): error TS1005: ';' expected.
```

test example:
```ts
export function hexadecimalDouble(): double {
   return 0x1.0c6f7a0b5ed8dp-20;
}
```

It seems ts recognize ```0x1.0c6f7a0b5ed8dp-20``` as property but I can't avoid this behaviour

**Comment by dcodeIO** [comment]
TS itself is not supporting this notation? If so, there isn't anything we we can do about this - everything needs to be compatible with TS.

**Comment by MaxGraey** [comment]
Javascript doesn't support this and obviously ts as well. But another word is ```wasm```. And I think ```fma``` (Post MVP) would be support only hexadecimals. With ts transpiler we can easely create custom transformer which can easily convert this literals to ```Number```.

**Comment by dcodeIO** [comment]
If you know how to do this in a way compatible with VSCode and other IDEs doing syntax highlighting, well, you can try. I'd probably just add a builtin that creates floats from bits.

**Comment by MaxGraey** [comment]
VSCode allow to install custom language grammars as well as Atom and etc, so it's not a big issue, but converting hexadecimals in runtime I think is not right way.

**Comment by dcodeIO** [comment]
Closing this for now. To recap: I'd like to stay compatible with TypeScript syntax so existing tooling can be reused. Features like these could be implemented as built-in functions in the future, though, either taking i32/i64 bits or a string as arguments.
