### ISSUE TITLE
User wants to have global variable support

### ISSUE THREAD

**Issue by nidin** [dcodeIO/AssemblyScript#19]
**What?**
Add global variable support 
```typescript
/// <reference path="../assembly.d.ts" />

let status:int = 1;

export function change(value:int):void {
    status = value;
}

export function getStatus():int {
    return status;
}
```

**Comment by dcodeIO** [comment]
Working on this atm. Unfortunately, there is no set_global/get_global in binaryen.js yet, so I might have to add this there first.

**Comment by nidin** [comment]
globals are immutable in wasm1, its good for constants. I am allocating global variables in memory in TurboScript.

**Comment by MaxGraey** [comment]
globals may be mutable or immutable. It's depend on declaration: ```global i32 immutable``` or ```global i32```

**Comment by nidin** [comment]
@MaxGraey You are correct, My thoughts was from old spec.

**Comment by dcodeIO** [comment]
Blocked by: https://github.com/WebAssembly/binaryen/issues/1028

**Comment by dcodeIO** [comment]
Basic global variable access should be working now.
