### ISSUE TITLE
Status of Array implementation

### ISSUE THREAD

**Issue by nidin** [dcodeIO/AssemblyScript#20]
@dcodeIO Are you planning to or implementing Array in AssemblyScript. 
I am ready for contribution, waiting to see your design.

**Comment by dcodeIO** [comment]
Probably, yes, once there are pointers and memory access this should be doable.

**Comment by dcodeIO** [comment]
There is some very basic array support now. Basically, an array must be instantiated with its exact, fixed size and the only provided property besides its elements is `length`. Cannot be used within expressions yet (i.e. something = (a[0] = 2)`, but expression statements should work (i.e. `a[0] = 2`).

**Comment by dcodeIO** [comment]
Basic array support should be done, except literal array initializers as now [tracked here](https://github.com/dcodeIO/AssemblyScript/issues/70). Both `Array<int>` and `int[]` notation are supported. The standard library is certainly lacking a lot of useful utility, but that isn't directly related to the core implementation.
