### ISSUE TITLE
Reinterpretations i32.reinterpret/f32 and etc

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#21]
I thinking about best way to implement this in Typescript notation. Keyword ```as``` already use for explicit type conversion so we need something different. Any idea?

**Comment by dcodeIO** [comment]
what about `reinterpret<int>(someFloat);` similar to the proposed sizeof<T>(); builtins?

**Comment by MaxGraey** [comment]
Are AssemblyScript already provide pointer arithmetics? In this case we can do something like:
```ts
let f: float = 1e-3; 
let floatAsUint: uint = (f as uint&);
```
or
```ts
let floatAsUint: uint = *<uint*>&f;
```

And after that wrap this to ```reinterpret``` func

**Comment by dcodeIO** [comment]
There is no pointer arithmetic yet and it is also not planned to implement that like it is in C. Instead, there is the proposed generic `Ptr<T>`. This is more like IntPtr in C# because there is no pointer arithmetic in TS.

**Comment by MaxGraey** [comment]
How about something kind this?
```
let floatAsUint: uint = (f as Ptr<float>) as uint;
```

**Comment by dcodeIO** [comment]
Here is what's planned: https://github.com/dcodeIO/AssemblyScript/blob/master/assembly.d.ts#L38

**Comment by MaxGraey** [comment]
What if extend Ptr to make it like [IntPtr's in C#](https://msdn.microsoft.com/ru-ru/library/system.intptr(v=vs.110).aspx)?

**Comment by dcodeIO** [comment]
Having it work mostly like in C# is a good idea I believe.

**Comment by MaxGraey** [comment]
It seems its now work:

```ts
export function cast(a: int): float {
  return reinterpretf(a);
}
```

Output
```
TypeError: Cannot read property 'parameterTypes' of undefined
```

**Comment by MaxGraey** [comment]
great, not everything fine
