### ISSUE TITLE
Browser's bundle error: 'useCaseSensitiveFileNames' owner is undefined

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#31]
![Error screenshop](https://www.dropbox.com/s/izcf8g7xijbjpw1/error-wasm-boundle.jpg?raw=1)

More info:
into **diagnostics.js**
```js
exports.defaultFormatDiagnosticsHost = {
    getCurrentDirectory: function () { return ts.sys.getCurrentDirectory(); },
    getNewLine: function () { return ts.sys.newLine; },
    getCanonicalFileName: ts.createGetCanonicalFileName(ts.sys.useCaseSensitiveFileNames) // <-- ts.sys is undefined
};
```

```ts``` object dump:
![debug-info](https://www.dropbox.com/s/pugqtjtkqrnd9i9/wasm-debug-stack.jpg?raw=1)

**Comment by dcodeIO** [comment]
This simply adds a sys implementation for the browser. I didn't test this, and it can probably be improved a lot, but the necessary infrastructure should be there now!

**Comment by MaxGraey** [comment]
It seems this issue resolved, but I have another one. Compiler object not present in global space:

Window object dump:
![Window Object Dump](https://www.dropbox.com/s/0lvpj7kbf2l5q7w/compiler-not-found.jpg?raw=1)

**Comment by MaxGraey** [comment]
And after last refactoring the issue was back!

**Comment by MaxGraey** [comment]
ok. And can you check browser compatibility after all that changes? It seems Compiler object not present in global scpace, but ```Binaryen```, ```ts``` and others are exists

**Comment by dcodeIO** [comment]
That one [should be there](https://github.com/dcodeIO/AssemblyScript/blob/master/src/compiler.ts#L1035) now.

**Comment by MaxGraey** [comment]
Unfortunately problem still exists. I'm using react.js + babal and when I try importing bundle as module I catch memory fault: "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory", It seems file is huge for babel processing. So I decide include bundle as ordinal script but I have problem with global visibility =(

**Comment by dcodeIO** [comment]
Going to wrap everything in an index file now, so there'll be a single global `assemblyscript` that holds all the things.

**Comment by dcodeIO** [comment]
I assume running this through babel or any other transpiler isn't a good fit, btw. Both typescript and binaryen are rather huge compiled and minified dependencies. That's also one of the reasons why webpack doesn't work properly here (for instance, this is not building typescript from source but bundling the npm package that provides a prebuilt js file).

**Comment by MaxGraey** [comment]
Yep! Now it works!
I thought about splitting **as** and **typescript** as well, but have the same reason as you, so I understand this is not possible yet.
