### ISSUE TITLE
Browser compatibility. Diagnostics and error printing.

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#37]
To finish integration of AssemblyScript with browser playground I should retrieve diagnostic errors when compiler can't process existing code. But ```AS``` use a lot of node specific ```process.stderr.write``` for that. So I thinking of best way to resolve this.

**Comment by dcodeIO** [comment]
As a starting point, there is the [silent](https://github.com/dcodeIO/AssemblyScript/blob/master/src/compiler.ts#L34) option to suppress printing to stderr. You can then manually manage [diagnostics](https://github.com/dcodeIO/AssemblyScript/blob/master/src/compiler.ts#L46).

**Comment by MaxGraey** [comment]
Of coarse I use silent option, and everything ok until input code is correct. And sometimes compileString sometimes call ```process.stderr.write```

**Comment by dcodeIO** [comment]
Hmm, are you calling `validate()` on the module? Just asking because that's a binaryen function hard-wired to output text format to console on validation errors.
