### ISSUE TITLE
Global declarated arrays cause to crash

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#39]
**Example:**
```ts
let array: Array<float> = new Array<float>(3);
```

**Error**:
out/expressions/new.js:76:
```js
  73 | var op = compiler.module;
  74 | var sizeArgument = compiler.maybeConvertValue(sizeArgumentNode, compiler.compileExpression(sizeArgumentNode, compiler.uintptrType), typescript.getReflectedType(sizeArgumentNode), compiler.uintptrType, false);
  75 | var uintptrCategory = binaryen.categoryOf(compiler.uintptrType, compiler.module, compiler.uintptrSize);
> 76 | var newsize = compiler.currentFunction.localsByName[".newsize"] || compiler.currentFunction.addLocal(".newsize", compiler.uintptrType);
  77 | var newptr = compiler.currentFunction.localsByName[".newptr"] || compiler.currentFunction.addLocal(".newptr", compiler.uintptrType);
  78 | var binaryenPtrType = binaryen.typeOf(compiler.uintptrType, compiler.uintptrSize);
  79 | // *(.newptr = memset(malloc(uintptrSize + size * (.newsize = EXPR)), 0, .newsize) = .newsize
```

**Comment by dcodeIO** [comment]
Hmm, yeah, `new` is currently bound to be called within a function. In this case, the initializer should go to `.executeGlobalInitializers`, though. Need to look into that.

**Comment by MaxGraey** [comment]
It seems for global declared arrays assignment not working:

```ts
let array: float[] = new Array<float>(3);
array[0] = 1.0; // <-- Assertion failed: mappedFunctions.count(name), at: src/wasm/wasm-binary.cpp,342, getFunctionIndex
```

**Comment by dcodeIO** [comment]
Where are you using the second line? In global scope? If so, there is no global scope, everything must happen within a function, i.e.:

```ts
let array: float[] = new Array(3);

function start(): void {
  array[0] = 1.0;
}
```

**Comment by MaxGraey** [comment]
Yes, assignment in global space. Is this not implemented yet?

**Comment by dcodeIO** [comment]
This could be implemented by moving everything happening within the global scope into a start function. The reason that it's not there yet is, though, that in WebAssembly, there is the `start` function, and you can't technically do anything on a global level otherwise.

Two options: Either implement a better error, or move everything into start implicitly.

**Comment by MaxGraey** [comment]
Second option like me much better because it compatible with typescript approaches. So if every modules have its own main subroutines and every launch in order to import, I think it's ok. But still need more investigations

**Comment by dcodeIO** [comment]
Btw, when I compile this:

```ts
let globalArr: uint[] = new Array(10);
globalArr[0] = 1;
```

I get the following error:

```
7 globalArr[0] = 1;
  ~~~~~~~~~~~~~~~~~

tests/test.ts(7,1): error TS-AS: Unsupported top-level statement: ExpressionStatement
```

which seems correct in this context.

**Comment by MaxGraey** [comment]
I got the same.

**Comment by dcodeIO** [comment]
How did you get `// <-- Assertion failed: mappedFunctions.count(name), at: src/wasm/wasm-binary.cpp,342, getFunctionIndex` then?

**Comment by MaxGraey** [comment]
I just copy from console in Chrome because copy text from faded notification little bit problematic) I though errors mirror to browser's console, but seems you silent all error messages, but it's good, I just implement own printing

**Comment by MaxGraey** [comment]
So it seems it's error that I got before
