### ISSUE TITLE
buildin (internal) namespace for internal operations

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#45]
**Now**
```ts
let sqrt3: float64 = sqrt(3.0);
let doubleAsInt64: int64 = reinterpretl(sqrt3);
```

**Proposal**
```ts
let sqrt3: float64 = buildin.sqrt(3.0);
let doubleAsInt64: int64 = buildin.reinterpretl(sqrt3);

// or as C-style intrinsics (looks ugly in my opinion)

let sqrt3: float64 = __buildin__sqrt(3.0);
let doubleAsInt64: int64 = __buildin__reinterpretl(sqrt3);
```
**Why?**
It resolve possible namespace conflicts. With this we can use our own ```sqrt```, ```floor``` and etc functions and identifiers.

Thoughts?

**Comment by RangerMauve** [comment]
Maybe the internal operations could be `import`ed so that the local name could be whatever they want or individual functions could be brought into scope. This would also make it easier to polyfill in order to make it compile to regular typescript.

Also, would `std` be a better name for something like this?

**Comment by dcodeIO** [comment]
This should already be possible to some extend. The compiler uses TypeScript's checker to resolve the reference to a function's actual declaration. While there will probably still be some issues regarding this, one thing that should actually work already is placing your custom version of `sqrt` into an imported file. This way, it's internal name will differ from the builtin one.

For the main file, it should be possible to fix this by changing the internal name of builtins declared in assembly.d.ts to something different, without the need for the user to rename their functions at all.

**Comment by MaxGraey** [comment]
WebAssembly/binaryen#1050 Cool!

**Comment by dcodeIO** [comment]
With this commit, it should now be possible to simply redefine the builtins without conflicts, even within the main file.
