### ISSUE TITLE
AssemblyScript Doesn't Suppport non-integer types with comparators

### ISSUE THREAD

**Issue by SanatSharma** [dcodeIO/AssemblyScript#56]
Hi, will AssemblyScript support non-integer computations with comparators? Currently a == b only works if both a and b are integers. 

Currently the wasm code generated for the following function:

export function test(): double{
    let a: double = 4;
    let b: double = 5;
     if(a == b)
          return a;   
  return b;
}

does not work since the == operator is seeking an int32 number while a and b are 64b numbers. Would this behavior be changed in the future?

**Comment by MaxGraey** [comment]
It seems problem with reinterpret type for floats. This code: 
```ts
export function test(): float32 {
    return 1.0;
}
```
produce current error:
```module.ts(2,12): error TS-AS: Illegal implicit conversion: 'int' to 'float'```

**Comment by dcodeIO** [comment]
Both of these cases should actually be working, going to look into it. We really need some test cases.

**Comment by dcodeIO** [comment]
This commit should cover the `return 1.0` case.

**Comment by apurvaraman** [comment]
The wasm code generated by the same function with long instead of double also fails to compile with operators like == (the type of the opcode for getlocal is set to i32 rather than i64).
