### ISSUE TITLE
Opcodes emitted for long not correct

### ISSUE THREAD

**Issue by apurvaraman** [dcodeIO/AssemblyScript#57]
The wasm code generated by the function below fails to compile (the opcode for the comparison is i32.eq rather than i64 but the getlocal is an i64).

```
export function test(): long{
let a: long = 4;
let b: long = 5;
if(a == b){
return a;
}
return b;
}
```

**Comment by dcodeIO** [comment]
Just tested with on master (there is one additional commit probably since you checked) and it emits the following s-expressions:

```s
 (func $test3 (type $I) (result i64)
  (local $0 i64)
  (local $1 i64)
  (set_local $0
   (i64.const 4)
  )
  (set_local $1
   (i64.const 5)
  )
  (if
   (i32.and
    (i64.eq
     (get_local $0)
     (get_local $1)
    )
    (i32.const 1)
   )
   (return
    (get_local $0)
   )
  )
  (return
   (get_local $1)
  )
 )
```

Validates and looks correct to me on a first glance, or am I overlooking something?

**Comment by apurvaraman** [comment]
I pulled the latest commit and now get the same s-expressions, but when I run the bytecode in the browser, I now get Uncaught TypeError: invalid type.

**Comment by dcodeIO** [comment]
Looks like some textual output sneaked into the wasm file. I wonder if that's from npm or something.

**Comment by dcodeIO** [comment]
The error I see within Firefox is `TypeError: cannot pass i64 to or from JS`. That's a limitation of the WebAssembly runtime because JS doesn't have safe 64-bit numbers.

**Comment by apurvaraman** [comment]
Looks like that was the issue. Thank you.
