### ISSUE TITLE
Can't compile tests with new defined methods

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#59]
I move forward and [implement isNaN and isFinite global methods](https://github.com/MaxGraey/AssemblyScript/commit/2b7c66bd460872879e4197edeb178cc570875b91), but can't compile to wasm:

```bash
initialization took 30.853 ms

/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:26
function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=
                                  ^
Assertion failed: functionsMap.find(curr->name) == functionsMap.end(), at: src/wasm/wasm.cpp,642,addFunction at Error
    at wa (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:8:170)
    at ___assert_fail (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:561:379)
    at Array.Aq (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:576:107015)
    at Object.Lma [as dynCall_vii] (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:582:103690)
    at invoke_vii (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:554:110)
    at Object.Bh [as _BinaryenAddFunction] (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:574:92951)
    at /Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:649:65
    at G (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:23:243)
    at Ua.a.Module.addFunction (/Volumes/Archive/Projects/Github/AssemblyScript/node_modules/binaryen/index.js:649:43)
    at Compiler.compileFunction (/Volumes/Archive/Projects/Github/AssemblyScript/src/compiler.ts:712:42)
```

**Comment by dcodeIO** [comment]
assembly.d.ts is currently limited to built-in functions and standard classes. Let me see what I can do about standard _functions_ ...

**Comment by MaxGraey** [comment]
Do you mean hardcoded reflection but for functions [like this](https://github.com/dcodeIO/AssemblyScript/blob/965048f8f1b63bde46a3c400b15f1921e28f8b6f/src/reflection/class.ts#L63)?

**Comment by dcodeIO** [comment]
The way it currently works is that in `assembly.d.ts` there is a decorator `@__impl` specifying the name of the class that implements a declared class. The first initialized class of that name is than used as the implementation. That's limited to functions currently.

Regarding `isNaN` and `isFinite` I figured that these might ideally be builtins resulting in the respective opcodes directly. For instance, `isNaN`can be implemented as `value != value`, while `isFinite` requires a few `op.select`s probably.

**Comment by dcodeIO** [comment]
Let me know if this is working as intended!

**Comment by MaxGraey** [comment]
Hmm, you think this should hard-coded? Can you update dist folder with new bundle plz?

**Comment by MaxGraey** [comment]
And what is side effects are expected without using ```select``` with temporary variables?

**Comment by dcodeIO** [comment]
`isNaN(a += 1)`, for example. On the opcode level, we are using the entire expression, not just the result. That's why we need a temp var.

**Comment by MaxGraey** [comment]
It seems this can avoid if use global definition functions in std instead use hard-coded buildins, what do you think? I don't see any reason to make isNaN and isFinite hard-coded. Is this limitation of current compile stage?

**Comment by dcodeIO** [comment]
Why would you want to avoid inlining a simple function like that? The optimizer will do exactly this anyway, provided the function isn't exported.
