### ISSUE TITLE
input func params interpret as returned type

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#6]
For example:

```ts
function add(a: int, b: int): float {
     return a + b;
}
```
actually intepret as:
```ts
return ((a as float) + (b as float)) as float)
```
instead:
```ts
return ((a as int) + (b as int)) as float)
```
More sensitive example (I working on s.SyntaxKind.EqualsEqualsToken and other comparision tokens):
```ts
function add(a: float, b: float): bool {
     return a == b;
}
```
Interpret both parameters as boolean, that is not what we need)

**Comment by dcodeIO** [comment]
Yes that's not yet working. The type is propagated from the root AST node downwards atm, but it should be the exact inverse.

**Comment by MaxGraey** [comment]
Can this be fixed in current stage? Or does it require significant effort?

**Comment by dcodeIO** [comment]
Sure, this can be fixed. Keep in mind that I just started this project a couple of hours ago :D

**Comment by MaxGraey** [comment]
I know, but you speed of coding very impressed=)

**Comment by dcodeIO** [comment]
This is probably still flawed somehow, so let me know if you experience any additional issues :)

**Comment by MaxGraey** [comment]
Great! I'd test now and if I figure outing some issues I let you know
