### ISSUE TITLE
Minor improvments for NaNs

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#60]
According to [this](https://github.com/WebAssembly/testsuite/blob/master/f32.wast) NaN is ```nan:0x200000``` for floats and ```nan:0x4000000000000``` for doubles.

**Comment by dcodeIO** [comment]
`nan:0x200000` just means that it is the NaN value with that exact bit pattern. NaN is a range of values, actually. The global value in AssemblyScript is that of JavaScript's NaN, see: https://github.com/dcodeIO/AssemblyScript/blob/master/src/compiler.ts#L394

**Comment by MaxGraey** [comment]
ok, got it
