### ISSUE TITLE
How better interop with arrays between JS and AS?

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#65]
I'm thinking apply something like this approach:

**AS code (with export malloc)**
```ts
export function task(input: double[], output: double[], size: int) {
      for (let i = 0; i < size; i++) {
            output[i] = input[i]; // some routine
      }
}
```

**JS code**
```js
    var input = new Float64Array(len);
    var output = new Float64Array(len);
    var inputPtr = module.exports.malloc(input.length * 8);
    var outputPtr = module.exports.malloc(output.length * 8);
    var inputOffset = inputPtr / 8;
    var outputOffset = outputPtr / 8;
    module.F64.set(input, inputOffset);
    module.exports.task(inputPtr, outputPtr, len);
    output.set(module.F64.subarray(outputOffset, outputOffset + output.length));
    module.exports.free(inputPtr);
    module.exports.free(outputPtr);

    console.log(output);
```

Is this right or we can do this better?

**Comment by dcodeIO** [comment]
My idea so far was that you could simply return the pointer to an existing array from WebAssembly to JavaScript and use that to copy the data from memory. All you need to know for this basically is that an Array<T> in memory starts with its size N as an i32, followed by N elements of its type and that when you `return someArray` in WebAssembly, calling the respective function from JavaScript will return its pointer value (an i32 for WASM32).

From there on you can simply use the `module.U32` view to get the size, and then slice the elements without the need to copy anything. Likewise, when providing an array from JS to WebAssembly you'd `malloc` its including its leading size, and provide the pointer to the AS function.

**Comment by MaxGraey** [comment]
Sounds good. It will be perfect have some example and may be some utils to simplificate interop operations with memory on js side.

**Comment by MaxGraey** [comment]
Can I fill array from JS? Without call module.exports.setMyArray. Just like this?

**AS Code**
```ts
export function sum(array: double[], len: int32): double {
    let sum: double = 0.0;
    for (let i: int32 = 0; i < len; i++) {
        sum += array[i];
    }
    return sum;
}
```

**JS Code**
```js
const size = 8;
var ptr = module.exports.malloc(4 + 8 * size);
module.U32[ptr >>> 2] = size;
for (var i = 0; i < size; i++) {
   module.F64[((ptr + 4) >>> 3) + i] = 1.0;
}
let sum = module.exports.sum(((ptr + 4) >>> 3), size); // just sum of array elements
console.log('sum', sum);
```

But result is wrong.
**Result**:
sum: 1.780059088256344e-307

**Comment by dcodeIO** [comment]
Should be possible, yes, but it's also likely that something isn't working as expected still. Could also be an issue with byte order (WebAssembly is LE), haven't tried.

**Comment by MaxGraey** [comment]
Yes, I tried this:

```ts
export function sum(array: double[]): double {
     return array.length as double;
}
```
```js
const size = 8;
var ptr = module.exports.malloc(4 + 8 * size);
module.U32[ptr >>> 2] = size;
```

But always get **0**

**Comment by MaxGraey** [comment]
So instead  this:

```js
module.U32[ptr >>> 2] = size;
```
I should use this:
```js
writeUintLE(size, module.U8, ptr);
```
?

**Comment by dcodeIO** [comment]
Yes, you can try. Going to update the loader component with some utility now.

**Comment by MaxGraey** [comment]
I tried. Unfortunately not work=(

**Comment by dcodeIO** [comment]
Ok, [this](https://github.com/dcodeIO/AssemblyScript/blob/master/lib/loader/index.js) is completely untested and I have probably made a couple of mistakes there. But it should be a good starting point and give an idea how this could work.

**Comment by dcodeIO** [comment]
For reference: https://github.com/dcodeIO/AssemblyScript/blob/master/tests/interop.ts

**Comment by MaxGraey** [comment]
Excellent!

**Comment by MaxGraey** [comment]
```ts
export function test(array: double[]): double {
    let sum: double = 0.0;
    for (let i: int32 = 0; i < array.length; i++) {
        sum += array[i];
    }
    return sum;
}
```

```js
const size = 8;
let array = module.array.create(size, 8);
for (let i = 0; i < size; ++i)
    module.f64.set(array.base + i, 1.0);

console.log(module.exports.test(array.ptr));
```

Output:
``` 32.501960784313724 ```

Expected:
``` 8.0 ```

What I missed?

**Comment by dcodeIO** [comment]
`module.f64.set(array.base + i * 8, 1.0);`

**Comment by MaxGraey** [comment]
Yes, I tried. Result is completely bad

**Comment by dcodeIO** [comment]
There is an error in the loader code, must be `var fle = f8b[7] === 128;`

**Comment by MaxGraey** [comment]
After fixing. Result better, but still wrong **4224**

**Comment by dcodeIO** [comment]
Oh, float/double set sets the ptr, not the value. Sec...

**Comment by dcodeIO** [comment]
For reference: https://github.com/dcodeIO/AssemblyScript/blob/master/tests/interop.ts#L98

**Comment by MaxGraey** [comment]
Yep, I fixed in my local file. Now this works!
