### ISSUE TITLE
Poposal. Rename bool -> boolean that comatible with typescript

### ISSUE THREAD

**Issue by MaxGraey** [dcodeIO/AssemblyScript#7]
After type alias implementation we can define ```bool``` as alias of ```boolean``` if needed but I think ```boolean``` should be a native.

**Comment by MaxGraey** [comment]
I got it. So leave it to later

**Comment by dcodeIO** [comment]
For reference: https://github.com/dcodeIO/AssemblyScript/blob/master/assembly.d.ts#L23

Though, the basic type recognized by resolveType is still `bool`.

**Comment by dcodeIO** [comment]
The compiler now assumes `bool` for `boolean`, [see](https://github.com/dcodeIO/AssemblyScript/blob/master/src/compiler.ts#L961).
