### ISSUE TITLE
Implement Array literal 

### ISSUE THREAD

**Issue by ir2331** [dcodeIO/AssemblyScript#70]
Hi, I was wondering whether you were planning on building a transformers file that traverses the AST and transforms it if it encounters syntactic sugar. For example, right now you support initializing arrays with the newKeyword, yet in TypeScript you can also initialize arrays by:

`let list: int[] = [1, 2, 3];`

There is several cases like this, and it would be more beneficial if you traversed the AST before compiling and changed it to the syntax you already support to compile to wasm rather than writing the code to compile every case there is. The TypeScript compiler uses a file called transformers.ts to do this.

I would be willing to pull request this if you let me know its ok with you to implement it like this. Thanks

**Comment by dcodeIO** [comment]
Initializing arrays like this is actually planned. Not sure about transforms, though. Might be that implementing it right into the compiler is more efficient. For instance, each expression kind is handled by [its own dedicated file](https://github.com/dcodeIO/AssemblyScript/tree/master/src/expressions) already and simply adding additional files shouldn't be much of an issue.

**Comment by ir2331** [comment]
When were you planning on implementing support for initializing arrays like this? I can pull request it.

**Comment by dcodeIO** [comment]
If you'd like to give it a shot, feel free to do so!

**Comment by dcodeIO** [comment]
See: https://github.com/dcodeIO/AssemblyScript/pull/83
