### ISSUE TITLE
Generate both .wasm and .wat in a same command line

### ISSUE THREAD

**Issue by yahiko00** [dcodeIO/AssemblyScript#77]
Hi,

I would like to know, just for convenience, and maybe efficiency, wether or not it could be possible to generate both _.wasm_ (binary) and _.wat_ (text) files with a same command line.

In that respect, I am wondering if the flag `--text` instead of being exclusive, could be inclusive, adding a _.wat_ to the _.wasm_ file.

For instance, `$> asc module.ts --text -o module.wasm` would generate both _module.wasm_ and _module.wat_ since this last one has been provided as argument.

We could imagine another command: `$> asc module.ts --text mymod.txt -o module.wasm`
And in this case, the command would generate at _.wat_ file named _mymod.txt_ since it has been given in argument.

This way, `-o` and `--outFile` would only be dedicated to generate _.wasm_ files, which complies more to the TypeScript compiler logic.

**Comment by dcodeIO** [comment]
Should be trivial to implement. Going to take a look!

**Comment by dcodeIO** [comment]
This tries to retain the previous functionality (there are two different text formats) while adding an additional `--text-out` option. Might be that evaluation order isn't ideal yet in case this is mixed with stdout.

**Comment by yahiko00** [comment]
Just tried it out.

**1.** I refreshed my asc compiler: `yarn global add asc`
**2.** I checked this release has the new --text-out option: `asc`
```
 --text-out             Outputs text format alongside a binary using the given file name.
```
**3.** I compiled the example project: `asc module.ts --text-out module.wat --outFile module.wasm`
I get two files as expected: module.wasm, and module.wat.

However, the text file seem way to big to be "honest": **255 kilobytes**, instead of just 93 bytes (more or less) according to https://maxgraey.github.io/Assembleash/:
```
(module
 (type $iii (func (param i32 i32) (result i32)))
 (memory $0 1)
 (export "add" (func $add))
 (func $add (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (i32.add
   (get_local $0)
   (get_local $1)
  )
 )
)
```

For information, here is my _module.ts_:
```
export function add(a: int, b: int): int {
  return a + b;
}
```

This is probably a configuration issue on my side, but I fail to see where. Here is my _tsconfig.json_:
```
{
  "extends": "./node_modules/assemblyscript/tsconfig.assembly.json"
}
```
And there is a local package of AssemblyScript installed in the _node_modules/_ folder.

**Comment by dcodeIO** [comment]
By default, `asc` bundles memory management routines like malloc etc. That might be what you are seeing there. In this (simple) case memory management routines are not needed, so you can use `-m bare` to skip these.

**Comment by yahiko00** [comment]
I compiled according to your insight: `asc module.ts -m bare --text-ou module.wat --outFile module.wasm`
This is better... but for the binary file only which size has been reduced from 11 kilobytes to 245 bytes
However, no text file has been generated. It seems this option `-m` prevent `--text-out` from working.

**Comment by dcodeIO** [comment]
Is that the actual command you ran? Just asking because it specifies `--text-ou` instead of `--text-out`.

**Comment by yahiko00** [comment]
I've compiled according to your insight: `asc module.ts -m bare --text-out module.wat --outFile module.wasm`

This is better. The text file is now much slimmer although not as much as in the playground:
```
(module
 (type $iii (func (param i32 i32) (result i32)))
 (type $iv (func (param i32)))
 (type $iiii (func (param i32 i32 i32) (result i32)))
 (type $iIii (func (param i32 i64 i32) (result i32)))
 (type $ifii (func (param i32 f32 i32) (result i32)))
 (type $iFii (func (param i32 f64 i32) (result i32)))
 (type $III (func (param i64 i64) (result i64)))
 (type $ii (func (param i32) (result i32)))
 (type $II (func (param i64) (result i64)))
 (type $FF (func (param f64) (result f64)))
 (type $ff (func (param f32) (result f32)))
 (type $FFF (func (param f64 f64) (result f64)))
 (type $fff (func (param f32 f32) (result f32)))
 (type $fi (func (param f32) (result i32)))
 (type $FI (func (param f64) (result i64)))
 (type $if (func (param i32) (result f32)))
 (type $IF (func (param i64) (result f64)))
 (type $i (func (result i32)))
 (type $Fi (func (param f64) (result i32)))
 (global $assembly.d.ts/NaN f64 (f64.const nan:0x8000000000000))
 (global $assembly.d.ts/NaNf f32 (f32.const nan:0x400000))
 (global $assembly.d.ts/Infinity f64 (f64.const inf))
 (global $assembly.d.ts/Infinityf f32 (f32.const inf))
 (memory $0 1)
 (export "add" (func $add))
 (func $add (type $iii) (param $0 i32) (param $1 i32) (result i32)
  (return
   (i32.add
    (get_local $0)
    (get_local $1)
   )
  )
 )
)
```

Is there any reason the playground and the compiler give different results?

**Comment by dcodeIO** [comment]
Yes. the playground also optimizes the module. eliminating unnecessary module elements. You can achieve the same using `-O`.

**Comment by yahiko00** [comment]
Perfect!

**Comment by dcodeIO** [comment]
Feel free to reopen if there are still any issues!
