### ISSUE TITLE
Proposal: asconfig.json

### ISSUE THREAD

**Issue by yahiko00** [dcodeIO/AssemblyScript#80]
This is a proposal to allow to specify the `asc` compiler options through a configuration file, which will be used alongside _tsconfig.json_.

# Motivation #

It is a common practice to define parameters through a configuration file. It helps project management and source control.

# Design considerations #

There could be several ways to define parameters for the `asc` compiler. One could be to include them directly in the _tsconfig.json_. The main advantage would be to centralize all compilation options in only one file. The main drawback I can see, is an unwanted coupling with TypeScript: if the _tsconfig.json_ format evolves, this would impact the `asc` compiler. Also, since _tsconfig.json_ can be inherited, it would not be that simple to retrieve from it inherited values, specific to AssemblyScript.

That is why, it seems easier and safer to have as a first step a basic separate configuration file for CLI options.

# Example #

```
// asconfig.json
{
  "compilerOptions": {
    "outFile": "module.wasm"                  /* Specifies the output file name. Also recognizes .wast / .wat */
    "validate": false,                        /* Validates the module. */
    "optimize": false,                        /* Runs optimizing binaryen IR passes. */
    "silent": false,                          /* Does not print anything to console. */
    "target": "wasm64",                       /* Specifies the target architecture: 'wasm32' (default), 'wasm64' */
    "memoryModel": "malloc",                  /* Specifies the memory model to use / how to proceed with malloc etc.: 'malloc' (default), 'exportmalloc', 'importmalloc', 'bare'
    "textFormat": "sexpr",                    /* Specifies the text output format: 'sexpr' (default), 'linear'
    "textOut": true                           /* Outputs text format alongside a binary. */
  }
 }
```

**Comment by dcodeIO** [comment]
This should have been implemented meanwhile. Feel free to reopen if necessary!
