### ISSUE TITLE
Compiler option --textFile not working

### ISSUE THREAD

**Issue by yahiko00** [dcodeIO/AssemblyScript#84]
It is said in the _README.md_ file that the option `--textFile` is valid. But it seems that it is not for the moment:
`$> asc module.ts --textFile module.wat --optimize --memoryModel bare --outFile module.wasm`

**Expected behavior**: compilation without error

**Actual behavior**: no compilation and error

The former option name still works though:
`$> asc module.ts --text-out module.wat --optimize --memoryModel bare --outFile module.wasm`

**Comment by dcodeIO** [comment]
README.md describes asc from master. The npm package might not include the update yet.

**Comment by yahiko00** [comment]
I've installed (again) AssemblyScript:
`$> yarn add dcodeIO/AssemblyScript`

I've run the compiler with the --textFile option
`$> asc module.ts --textFile module.wat --optimize --memoryModel bare --outFile module.wasm`

Error:
```
initialization took 42.683 ms
compilation took 11.845 ms

C:\Users\Yahiko\AppData\Local\Yarn\config\global\node_modules\binaryen\index.js:26
function(e){if(!(e instanceof ha))throw e;});a.inspect=function(){return"[Emscripten Module object]"}}else if(La)a.print||(a.print=print),"undefined"!=typeof printErr&&(a.printErr=printErr),a.read="undefined"!=typeof read?read:function(){throw"no read() available";},a.readBinary=function(e){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(e));e=read(e,"binary");v("object"===typeof e);return e},"undefined"!=typeof scriptArgs?a.arguments=scriptArgs:"undefined"!=typeof arguments&&(a.arguments=
                                  ^

TypeError: Cannot read property 'available' of undefined
    at writeText (C:\Users\Yahiko\AppData\Local\Yarn\config\global\node_modules\assemblyscript\bin\asc.js:164:29)
    at C:\Users\Yahiko\AppData\Local\Yarn\config\global\node_modules\assemblyscript\bin\asc.js:142:7
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Without --textFile option, everythings fine:
`$> asc module.ts --optimize --memoryModel bare --outFile module.wasm`

**Comment by dcodeIO** [comment]
Most likely, the npm package (that also yarn installs) doesn't have the updated CLI arguments, yet.

**Comment by yahiko00** [comment]
Hmm, but I've retrieved AssemblyScript from your repo directly, not from npm.

**Comment by dcodeIO** [comment]
Oh, sorry, overlooked that. Can you spot any obvious issue in that regard [here](https://github.com/dcodeIO/AssemblyScript/blob/master/bin/asc.js)?

**Comment by yahiko00** [comment]
Ok, I will let you know ;)

**Comment by yahiko00** [comment]
It seems `assemblyscript.wabt` is not imported since it is `undefined` in the function `writeText`, and so, `assemblyscript.wabt.available` throws an error at runtime.

**Comment by dcodeIO** [comment]
wabt integration has changed slightly recently. There is no `wabt` subnamespace anymore, this is now part of `util`. If `assemblyscript.util.wabt` is defined, `wabt.js` has been loaded alongside the compiler and `assemblyscript.util.wasmToWast` etc. will work.

**Comment by yahiko00** [comment]
Ok. Another issue: now `argv` inside the `writeText` function is undefined, which is normal since argv is defined in the `main` function.

**Comment by dcodeIO** [comment]
I tackled this issue somewhere within the latest commits. Is it working for you now?

**Comment by yahiko00** [comment]
It works now :)
