### ISSUE TITLE
Unsupported Top-Level statement upon Array Initialization

### ISSUE THREAD

**Issue by SanatSharma** [dcodeIO/AssemblyScript#90]
Hi, I encountered the above error while trying to initialize my array.
let a: int[] = new Array(5);

//export function init(){
a[0] = 1;
a[1] = 2;
a[2] = 3;
a[3] = 4;
a[4] = 5;
//}

The code works when the initialization is done inside a function, but does not when it is initialized outside a function. Does this have to do with how globals work in the AssemblyScript compiler?

**Comment by dcodeIO** [comment]
Top level statements and expressions are not yet supported respectively it's yet to be decided how this should be implemented ideally. The closest to execution of top-level code probably is to eventually compile such statements as part of an implicit start function, which must be done explicitly currently ([example](https://github.com/dcodeIO/AssemblyScript/blob/master/tests/interop/array.ts#L5)).

**Comment by SanatSharma** [comment]
One possible way to do so would be to allow variable declarations at the start of a file(similar to how C allowed in its original implementations) and then bundle up those variables as part of the start function. However, I feel this approach would be highly limiting and goes against the way TypeScript behaves.

**Comment by yahiko00** [comment]
As far as I understand WebAssembly, there is no other way for the moment to execute code than importing/loading modules from a JavaScript main program.
This is unlikely to change anytime soon.
So I do not see as really risky to bet on a hidden _start_ function as an entry point of any WebAssembly module.

**Comment by dcodeIO** [comment]
The start function isn't really hidden, it's defined as its own section and called by WebAssembly. It's somewhat the equivalent of the main function in a C program.

**Comment by yahiko00** [comment]
Would it be possible to avoid defining explicitly this `start` function and tell the compiler to gather top level statements into a generated `start` function?

**Comment by dcodeIO** [comment]
Yeah, exactly that. We'd have to deal with top-level statements in multiple files, though, somehow calling all these start functions in proper order from the .wasm module's main start function.

**Comment by RangerMauve** [comment]
@dcodeIO Would that be possible by looking at the import statements?

Right now with ES Modules your dependencies get executed before your current file.

I think the same thing could be done for AssemblyScript modules

**Comment by dcodeIO** [comment]
It's definitively possible, yes. Just not implemented, yet.

**Comment by dcodeIO** [comment]
Implemented by https://github.com/dcodeIO/AssemblyScript/commit/cd526edda9038cb15cf99079ea0c305f73572394

There are still a couple of edge cases with `const` declarations that must be `let` because initialization must be performed after the runtime's `init` has been called, but that's nothing too dramatic for now.
