### ISSUE TITLE
How to access variables/functions inside AssemblyScript?

### ISSUE THREAD

**Issue by SanatSharma** [dcodeIO/AssemblyScript#92]
Hi, I am unable to access the length of a local array or any other declared variable inside AssemblyScript. Once the array is initialized, if I wish to call the inbuilt property such as length, I get the appropriate local variable and try to access the length but do not know how to do so. The length does not seem to be retained in memory anywhere. Also, when testing arrays, the .length operator returns a constant value, which means that it is not being stored correctly.

eg, the following function returns 1 when called.
export function getLength(): int {
  let v: int[] = new Array(9);
  v[0] = 1;
  v[1] = 17;
  v[2] = 15;
  v[3] = 71;
  v[4] = 17;
  v[5] = 16;
  v[6] = 14;
  v[7] = 32;
  v[8] = 12;
  
  return v.length;
}

**Comment by dcodeIO** [comment]
Just tested with master:

```
loading 'test.wasm' ...  index.html:48:3
> exports.memory  index.html:57:11
> exports.getLength(0)  index.html:55:11
loaded.  index.html:61:7
exports.getLength()
9
```

**Comment by dcodeIO** [comment]
Feel free to reopen if the issue still persists in master.
